name:                tuxedocat
version:             0.1.0.0
github:              "nfmccrina/tuxedocat"
license:             BSD3
author:              "Nathan McCrina"
maintainer:          "nathan.mccrina@outlook.com"
copyright:           "Copyright (c) 2018 Nathan McCrina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nfmccrina/tuxedocat#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- vector >= 0.12.0

library:
  source-dirs: src

executables:
  tuxedocat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tuxedocat

tests:
  tuxedocat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tuxedocat
    - HUnit
